const test=require('node:test');const assert=require('node:assert/strict');const C=require('../webroot/core.js');
test('stored configuration rejects unknown versions and malformed entries',()=>{
assert.throws(()=>C.normalizeConfig({schemaVersion:9}),/Unsupported schemaVersion/);
assert.throws(()=>C.normalizeConfig({schemaVersion:1,autoApplyOnBoot:false,apps:[{packageName:'x;id',followSystem:true}]}),/Invalid package/);
assert.throws(()=>C.normalizeConfig({schemaVersion:1,autoApplyOnBoot:false,apps:[{packageName:'com.x.app',followSystem:false,localeTag:'en;id'}]}),/Invalid Locale/);
});
test('shell quoting preserves literal apostrophes',()=>{assert.equal(C.shellQuote("a'b"),"'a'\"'\"'b'")});
test('validates package names and BCP-47 tag shape',()=>{assert.equal(C.validPackage('com.example.reader'),true);for(const x of ['com;id','-com.example','com.example;touch','one'])assert.equal(C.validPackage(x),false);assert.equal(C.validLocale('zh-Hans-CN'),true);assert.equal(C.validLocale('en-US'),true);for(const x of ['','en US','--locales','en;id','en\nfr','en-1'])assert.equal(C.validLocale(x),false)});
test('JSON/internal conversion round trips and rejects corrupted data',()=>{const c={schemaVersion:1,autoApplyOnBoot:true,apps:[{packageName:'com.example.a',followSystem:false,localeTag:'ja-JP'},{packageName:'com.example.b',followSystem:true}]};assert.deepEqual(C.parseInternal(C.toInternal(c)),C.normalizeConfig(c));assert.throws(()=>C.parseInternal('schema=1\nauto=1\napp=bad|en-US\n'),/Invalid package/);assert.throws(()=>C.parseInternal('schema=1\nauto=1\nwat=1\n'),/Unknown config/)});
test('system default locale output and locale failures are distinguished',()=>{assert.deepEqual(C.parseLocaleOutput('Locales for com.x.app for user 0 are []').followSystem,true);assert.equal(C.parseLocaleOutput('Locales for com.x.app for user 0 are [en-US]').localeTag,'en-US');assert.equal(C.parseLocaleOutput('Unknown package com.x').reason,'package-unavailable');assert.equal(C.parseLocaleOutput('cmd: not found').ok,false)});

test('device locale catalog parsing keeps valid unique BCP-47 tags only',()=>{const output=['en-US','zh-CN','invalid tag','en-US',''].join('\n');assert.deepEqual(C.parseDeviceLocales(output),['en-US','zh-CN'])});

test('package enumeration supports Manager bridge API variants',()=>{let calls=[];const bridge={listPackages(type){calls.push(type);return JSON.stringify(['com.example.user','bad;pkg'])},listAllPackages(){throw Error('should not be called')}};assert.deepEqual(C.packageNamesFromBridge(bridge),['com.example.user']);assert.deepEqual(calls,['all']);assert.deepEqual(C.packageNamesFromBridge({listAllPackages:()=>['com.example.sys']}),['com.example.sys']);assert.deepEqual(C.packageNamesFromBridge({listPackages:()=>[],listAllPackages:()=>['com.example.fallback']}),['com.example.fallback']);assert.deepEqual(C.packageNamesFromBridge({listUserPackages:()=>['com.example.user'],listSystemPackages:()=>['com.android.settings']}),['com.example.user','com.android.settings']);assert.equal(C.packageNamesFromBridge({}),null)});
test('pm package list fallback parses package-manager output',()=>{assert.deepEqual(C.packageNamesFromPm(['package:com.example.a','package:com.android.b','not-a-package'].join('\n')),['com.example.a','com.android.b'])});

test('validates numeric Android user IDs used by cmd locale',()=>{assert.equal(C.validUserId('0'),true);assert.equal(C.validUserId('12'),true);for(const x of ['', '-1', '0;id', '0\\n1'])assert.equal(C.validUserId(x),false)});
