(function(){
"use strict";
const C=window.LSCore;
const DATA="/data/adb/language_selector_ksu_data";
const CONFIG=DATA+"/config.v1";
const $=id=>document.getElementById(id);
const S={apps:[],selected:null,configs:{schemaVersion:1,autoApplyOnBoot:false,apps:[]},page:"apps",search:"",showSystem:false,loading:false,errors:[],operation:"",bootRaw:"",configValid:false,localeQuery:""};
const LANGUAGES=("af ar az be bg bn bs ca cs cy da de el en es et eu fa fi fil fr ga gl gu he hi hr hu hy id is it ja ka kk km kn ko lo lt lv mk ml mn mr ms mt my nb ne nl nn no pa pl pt ro ru sk sl sq sr sv sw ta te th tr uk ur uz vi zh zh-Hans zh-Hant").split(" ");
const REGIONS=("en-US en-GB en-AU en-CA en-IN en-NZ en-SG en-ZA es-ES es-MX es-AR es-CO es-CL es-US fr-FR fr-CA fr-BE fr-CH pt-BR pt-PT zh-CN zh-TW zh-HK zh-SG zh-Hans-CN zh-Hant-TW zh-Hant-HK ja-JP ko-KR de-DE de-AT de-CH it-IT nl-NL nl-BE ru-RU uk-UA ar-EG ar-SA hi-IN bn-BD bn-IN pa-IN ta-IN ta-LK te-IN ur-PK fa-IR id-ID ms-MY th-TH vi-VN fil-PH tr-TR pl-PL cs-CZ sk-SK hu-HU ro-RO bg-BG el-GR he-IL sv-SE da-DK nb-NO fi-FI").split(" ");
const COMMON=("en-US zh-CN zh-TW ja-JP ko-KR fr-FR de-DE es-ES pt-BR").split(" ");
const PRESETS=[["OnePlus Blue","#42A5F5"],["Golden","#CC6F4E"],["Lemon Yellow","#E6A545"],["Grass Green","#7DC22F"],["Charm Purple","#9575CD"],["Sky Blue","#26C6DA"],["Vigour Red","#F06292"],["Fashion Pink","#BA68C8"],["Material Blue","#2196F3"],["Teal","#009688"],["Green","#4CAF50"],["Red","#F44336"],["Orange","#FF9800"],["Purple","#9C27B0"],["Cyan","#00BCD4"],["Indigo","#3F51B5"],["Pink","#E91E63"],["Blue Grey","#607D8B"],["Deep Orange","#FF5722"],["Light Green","#8BC34A"],["LineageOS Teal","#009688"],["Classic Green","#009866"]];
let seq=0;
function api(){return typeof window.ksu==="object"&&window.ksu}
function parseNative(v){if(Array.isArray(v))return v;if(typeof v==="string"){try{return JSON.parse(v)}catch(e){throw Error("KernelSU API returned invalid JSON")}}return []}
function execAsync(command){return new Promise((resolve,reject)=>{if(!api()||typeof ksu.exec!=="function")return reject(Error("KernelSU Next root shell API unavailable"));const name="__ls_cb_"+(++seq);let done=false;const timer=setTimeout(()=>{if(done)return;done=true;delete window[name];reject(Error("Root command timed out"))},30000);window[name]=(code,out,err)=>{if(done)return;done=true;clearTimeout(timer);delete window[name];resolve({code:Number(code),out:String(out||""),err:String(err||"")})};try{ksu.exec(command,name)}catch(e){done=true;clearTimeout(timer);delete window[name];reject(e)}})}
function command(parts){return parts.join(" ")}
function getUser(){return execAsync("am get-current-user").then(r=>{const u=r.out.trim();if(r.code!==0||!/^\\d+$/.test(u))throw Error("Unable to determine current Android user");return u})}
function localeCommand(action,pkg,user,tag){if(!C.validPackage(pkg))throw Error("Invalid package name");if(!/^\\d+$/.test(user))throw Error("Invalid Android user");const q=C.shellQuote;let p=["cmd","locale",action,q(pkg),"--user",q(user)];if(action==="set-app-locales"&&tag!==undefined){if(tag!==""&&!C.validLocale(tag))throw Error("Invalid BCP-47 Locale tag");if(tag!=="")p.push("--locales",q(tag))}return command(p)}
function checkPlatform(){const sdk=Number(localStorage.getItem("lastSdk")||0);if(sdk&&sdk<33)throw Error("Android 13 or later is required")}
async function readLocale(pkg){try{checkPlatform();const user=await getUser();const r=await execAsync(localeCommand("get-app-locales",pkg,user));const parsed=C.parseLocaleOutput(r.out+"\n"+r.err);if(r.code!==0&&!parsed.ok)return{ok:false,reason:/not found|unknown command|not recognized/i.test(r.err+r.out)?"command-unavailable":parsed.reason,raw:r.err||r.out};if(!parsed.ok)return{ok:false,reason:parsed.reason,raw:parsed.raw};return parsed}catch(e){return{ok:false,reason:/Android 13/i.test(e.message)?"unsupported":/user/i.test(e.message)?"user-unavailable":"command-unavailable",raw:e.message}}}
function statusText(x){if(x&&x.ok)return x.followSystem?"Follow system default":x.localeTag||"Custom locale";const map={"package-unavailable":"Package not installed for current user","user-unavailable":"Current Android user unavailable","command-unavailable":"cmd locale unavailable or unsupported ROM","unsupported":"Android 13+ is required","read-failed":"Could not read app language"};return map[x?.reason]||"Language read failed"}
function nativeList(method){if(!api()||typeof ksu[method]!=="function")throw Error("Required KernelSU Next WebUI-Next API is unavailable: "+method);return parseNative(ksu[method]())}
async function loadConfig(){try{const r=await execAsync("if [ -f "+C.shellQuote(CONFIG)+" ]; then cat "+C.shellQuote(CONFIG)+"; else printf 'schema=1\\nauto=0\\n'; fi");if(r.code!==0)throw Error(r.err||"Cannot read config");S.configs=C.parseInternal(r.out);S.configValid=true}catch(e){S.configs={schemaVersion:1,autoApplyOnBoot:false,apps:[]};S.configValid=false;S.errors.push("Config: "+e.message)}}
async function saveConfig(next){const normalized=C.normalizeConfig(next),lines=C.toInternal(normalized).trimEnd().split("\n");const args=lines.map(C.shellQuote).join(" ");const q=C.shellQuote(CONFIG);const tmp=C.shellQuote(CONFIG+".tmp");const cmd="mkdir -p "+C.shellQuote(DATA)+" && chmod 0700 "+C.shellQuote(DATA)+" && printf '%s\\n' "+args+" > "+tmp+" && chmod 0600 "+tmp+" && mv -f "+tmp+" "+q;const r=await execAsync(cmd);if(r.code!==0)throw Error(r.err||r.out||"Configuration save failed");S.configs=normalized;S.configValid=true;localStorage.setItem("configSavedAt",new Date().toLocaleString());$("configUpdated").textContent="Saved "+localStorage.getItem("configSavedAt");$("autoSwitch").setAttribute("aria-checked",String(normalized.autoApplyOnBoot))}
function appSetting(pkg){return S.configs.apps.find(a=>a.packageName===pkg)}
function updateEntry(pkg,entry){const apps=S.configs.apps.filter(a=>a.packageName!==pkg);apps.push({packageName:pkg,followSystem:entry.followSystem===true,localeTag:entry.followSystem?null:entry.localeTag});return{schemaVersion:1,autoApplyOnBoot:S.configs.autoApplyOnBoot,apps}}
function announce(text){const t=$("toast");t.textContent=text;t.classList.add("show");setTimeout(()=>t.classList.remove("show"),2400)}
function shellEscapeHtml(){}
function showDialog(title,message,actions){const host=$("dialogHost");host.replaceChildren();const scrim=document.createElement("div");scrim.className="dialog-scrim";const d=document.createElement("div");d.className="dialog";const h=document.createElement("h2");h.textContent=title;const p=document.createElement("p");p.textContent=message;const row=document.createElement("div");row.className="dialog-actions";for(const a of actions){const b=document.createElement("button");b.textContent=a.label;b.onclick=()=>{host.replaceChildren();a.run&&a.run()};row.append(b)}d.append(h,p,row);scrim.append(d);host.append(scrim)}
function contrast(c1,c2){function lum(hex){const h=hex.replace("#","");const rgb=[0,2,4].map(i=>parseInt(h.slice(i,i+2),16)/255).map(v=>v<=.04045?v/12.92:((v+.055)/1.055)**2.4);return .2126*rgb[0]+.7152*rgb[1]+.0722*rgb[2]}const a=lum(c1),b=lum(c2);return(Math.max(a,b)+.05)/(Math.min(a,b)+.05)}
function mix(fg,bg,p){const a=fg.replace("#",""),b=bg.replace("#","");return"#"+[0,2,4].map(i=>Math.round(parseInt(a.slice(i,i+2),16)*p+parseInt(b.slice(i,i+2),16)*(1-p)).toString(16).padStart(2,"0")).join("")}
function theme(){const mode=localStorage.getItem("ls.theme")||"system";const dark=mode==="dark"||(mode==="system"&&matchMedia("(prefers-color-scheme: dark)").matches);document.body.classList.toggle("dark",dark);$("themeSelect").value=mode;let accent=localStorage.getItem("ls.accent")||"#42a5f5";if(dark)accent=mix(accent,"#121212",.78);const surface=dark?"#212121":"#ffffff";let ink=accent;for(let p=.9;p>=.25&&contrast(ink,surface)<4.5;p-=.08)ink=mix(accent,dark?"#ffffff":"#000000",p);const on=contrast(accent,"#fff")>=contrast(accent,"#000")?"#fff":"#000";document.documentElement.style.setProperty("--accent",accent);document.documentElement.style.setProperty("--accentInk",ink);document.documentElement.style.setProperty("--tonal",mix(accent,surface,dark?.18:.12));document.documentElement.style.setProperty("--onAccent",on);$("accentColor").value=localStorage.getItem("ls.accent")||"#42a5f5"}
function renderPresets(){const p=$("presets");p.replaceChildren();for(const [name,color]of PRESETS){const b=document.createElement("button");b.className="swatch";b.title=name;b.setAttribute("aria-label",name+" "+color);b.style.backgroundColor=color;b.onclick=()=>{localStorage.setItem("ls.accent",color);theme()};p.append(b)}}
function setPage(page){S.page=page;S.selected=null;const pages={apps:"appsPage",settings:"settingsPage",diagnostics:"diagnosticsPage",detail:"detailPage"};for(const [k,id]of Object.entries(pages))$(id).classList.toggle("hidden",page!==k);$("back").classList.toggle("hidden",page!=="detail");$("refresh").classList.toggle("hidden",page==="settings");$("title").textContent=page==="detail"?(S.selected?.appLabel||"App language"):page==="settings"?"Settings":page==="diagnostics"?"Diagnostics":"Language Selector";document.querySelectorAll(".nav-button").forEach(b=>b.classList.toggle("active",b.dataset.page===page));if(page==="diagnostics")loadDiagnostics()}
function openDetail(app){S.selected=app;S.page="detail";$("appsPage").classList.add("hidden");$("detailPage").classList.remove("hidden");$("settingsPage").classList.add("hidden");$("diagnosticsPage").classList.add("hidden");$("back").classList.remove("hidden");$("title").textContent=app.appLabel||app.packageName;const head=$("appHeader");head.replaceChildren();const icon=document.createElement("img");icon.className="app-icon";icon.src=app.icon||("ksu://icon/"+encodeURIComponent(app.packageName));icon.alt="";const copy=document.createElement("div");const name=document.createElement("div");name.className="app-name";name.textContent=app.appLabel||app.packageName;const pkg=document.createElement("div");pkg.className="package";pkg.textContent=app.packageName;copy.append(name,pkg);head.append(icon,copy);$("currentLocale").textContent="Reading…";readLocale(app.packageName).then(result=>{$("currentLocale").textContent=statusText(result)+(result.ok&&!result.followSystem?" ("+result.localeTag+")":"");if(!result.ok)recordError(app.packageName+": "+statusText(result)+" — "+result.raw)});renderLocales()}
function langLabel(tag){try{const [lang,...rest]=tag.split("-");const disp=new Intl.DisplayNames([navigator.language||"en"],{type:"language"});const base=disp.of(lang);return rest.length?base+" · "+rest.join("-"):base}catch(e){return tag}}
function renderLocales(){const q=S.localeQuery.trim().toLowerCase();for(const id of ["commonLocales","localeList"]){const host=$(id);host.replaceChildren();const list=id==="commonLocales"?COMMON:LANGUAGES.concat(REGIONS).filter(t=>!COMMON.includes(t));const tags=[...new Set(list)].filter(C.validLocale).filter(t=>!q||t.toLowerCase().includes(q)||langLabel(t).toLowerCase().includes(q));for(const tag of tags){const b=document.createElement("button");b.className="locale-option";b.innerHTML="";const title=document.createElement("span");title.textContent=langLabel(tag);const sub=document.createElement("small");sub.textContent=tag;b.append(title,sub);b.onclick=()=>applyLocale(tag);host.append(b)}}}
async function applyLocale(tag){const app=S.selected;if(!app||!C.validLocale(tag))return;showDialog("Apply language","Set "+tag+" for "+app.packageName+"? The app may need to restart to display the change.",[{label:"Cancel"},{label:"Apply",run:async()=>{await performLocale(app,tag)}}])}
async function restoreDefault(){const app=S.selected;if(!app)return;showDialog("Follow system default","Clear the app-specific Locale list for "+app.packageName+"?",[{label:"Cancel"},{label:"Restore",run:async()=>{await performLocale(app,null)}}])}
async function performLocale(app,tag){announce("Applying…");try{checkPlatform();const user=await getUser();const cmd=tag===null?localeCommand("set-app-locales",app.packageName,user):localeCommand("set-app-locales",app.packageName,user,tag);const result=await execAsync(cmd);if(result.code!==0)throw Error(result.err||result.out||"cmd locale returned "+result.code);const actual=await readLocale(app.packageName);const matches=actual.ok&&(tag===null?actual.followSystem:(!actual.followSystem&&actual.localeTag.split(",")[0].trim()===tag));if(!matches)throw Error(actual.ok?"Command returned success but verification did not match: "+statusText(actual):statusText(actual)+" "+actual.raw);try{await saveConfig(updateEntry(app.packageName,{followSystem:tag===null,localeTag:tag}))}catch(e){recordError("Language changed, config save failed: "+e.message);$("currentLocale").textContent="Applied; configuration save failed";announce("Language applied; save failed");return}S.operation=(tag===null?"Restored system default for ":"Set "+tag+" for ")+app.packageName;localStorage.setItem("lastOperation",S.operation);$("currentLocale").textContent=tag===null?"Follow system default":tag;announce("Verified: "+(tag||"system default"))}catch(e){recordError(e.message);S.operation="Failed: "+app.packageName+" — "+e.message;localStorage.setItem("lastOperation",S.operation);$("currentLocale").textContent="Failed: "+e.message;announce("Language change failed")}}
function recordError(x){S.errors.unshift(new Date().toISOString()+" "+x);S.errors=S.errors.slice(0,30);localStorage.setItem("ls.errors",JSON.stringify(S.errors))}
function iconData(value){if(!value)return"";if(value.startsWith("data:image"))return value;return"data:image/png;base64,"+value}
async function yieldTask(){return new Promise(resolve=>setTimeout(resolve,0))}
async function loadApps(){if(S.loading)return;S.loading=true;$("listStatus").textContent="Loading installed apps…";$("appList").replaceChildren();try{const names=nativeList("listAllPackages");const unique=[...new Set(names.filter(C.validPackage))];if(!unique.length){$("listStatus").textContent="No installed apps returned by KernelSU Next.";S.apps=[];return}
const all=[];for(let i=0;i<unique.length;i+=60){const batch=unique.slice(i,i+60);try{if(typeof ksu.getPackagesInfo!=="function")throw Error("Package info API unavailable");const infos=parseNative(ksu.getPackagesInfo(JSON.stringify(batch)));all.push(...infos)}catch(e){S.errors.push("Some package details could not be read: "+e.message)}$("listStatus").textContent="Reading app details "+Math.min(i+60,unique.length)+" / "+unique.length;await yieldTask()}
let icons=[];if(typeof ksu.getPackagesIcons==="function"){for(let i=0;i<unique.length;i+=40){try{icons.push(...parseNative(ksu.getPackagesIcons(JSON.stringify(unique.slice(i,i+40)),48)))}catch(e){break}await yieldTask()}}
const iconMap=new Map(icons.map(x=>[x.packageName,iconData(x.icon)]));const infoMap=new Map(all.map(x=>[x.packageName,x]));S.apps=unique.map(pkg=>{const x=infoMap.get(pkg)||{};return{packageName:pkg,appLabel:x.appLabel||pkg,isSystem:!!x.isSystem,icon:iconMap.get(pkg)||"",locale:null}});$("listStatus").textContent="Reading app languages… 0 / "+S.apps.length;let i=0,at=0;async function worker(){while(at<S.apps.length){const idx=at++,app=S.apps[idx];app.locale=await readLocale(app.packageName);i++;if(i%10===0||i===S.apps.length)$("listStatus").textContent="Reading app languages… "+i+" / "+S.apps.length;}}await Promise.all(Array.from({length:4},worker));const failed=S.apps.filter(a=>!a.locale.ok).length;$("listStatus").textContent=S.apps.length+" apps loaded"+(failed?" · "+failed+" language status unavailable":"");renderApps()}catch(e){$("listStatus").textContent="Could not load apps: "+e.message;S.errors.unshift(e.message);recordError("App list: "+e.message)}finally{S.loading=false}}
function renderApps(){const host=$("appList");host.replaceChildren();const query=$("search").value.trim().toLowerCase();const list=S.apps.filter(a=>(S.showSystem||!a.isSystem)&&(!query||a.appLabel.toLowerCase().includes(query)||a.packageName.toLowerCase().includes(query)));if(!list.length){const p=document.createElement("div");p.className="statusline";p.textContent=S.apps.length?"No apps match this filter.":"No apps available.";host.append(p);return}for(const app of list){const b=document.createElement("button");b.className="app-row";const img=document.createElement("img");img.className="app-icon";img.alt="";img.src=app.icon||("ksu://icon/"+encodeURIComponent(app.packageName));img.onerror=()=>{img.onerror=null;img.src="data:image/svg+xml,"+encodeURIComponent('<svg xmlns="http://www.w3.org/2000/svg" width="48" height="48"><rect width="48" height="48" fill="#eeeeee"/><text x="24" y="30" text-anchor="middle" font-size="20" fill="#757575">'+(app.appLabel||"?").slice(0,1).replace(/[<&]/g,"")+'</text></svg>')};const copy=document.createElement("div");copy.className="app-copy";const name=document.createElement("div");name.className="app-name";name.textContent=app.appLabel;const pkg=document.createElement("div");pkg.className="package";pkg.textContent=app.packageName;const loc=document.createElement("div");loc.className="locale-state";loc.textContent=statusText(app.locale);copy.append(name,pkg,loc);b.append(img,copy);b.onclick=()=>openDetail(app);host.append(b)}}
async function loadDiagnostics(){const host=$("diagnostics");host.replaceChildren();const rows=[];let sys="",sdk="",cmd="";try{const r=await execAsync("getprop ro.build.version.release; getprop ro.build.version.sdk");[sys,sdk]=r.out.trim().split(/\r?\n/)}catch(e){}localStorage.setItem("lastSdk",sdk||"0");try{const r=await execAsync("command -v cmd >/dev/null 2>&1 && cmd locale help >/dev/null 2>&1 && printf available || printf unavailable");cmd=r.out.trim()}catch(e){cmd="unavailable"}rows.push(["Android",sys?sys+" (API "+sdk+")":"Unavailable"],["KernelSU Next WebUI/API",api()&&typeof ksu.listAllPackages==="function"&&typeof ksu.getPackagesInfo==="function"&&typeof ksu.exec==="function"?"Available":"Required WebUI-Next APIs unavailable"],["Package icons",api()&&typeof ksu.getPackagesIcons==="function"?"Available":"Icon API unavailable; manager URI fallback"],["cmd locale",cmd||"unavailable"],["Configuration",S.configValid?"Valid":"Missing or invalid; auto-apply disabled"],["Last saved",localStorage.getItem("configSavedAt")||"Not recorded"]);for(const [k,v]of rows){const dt=document.createElement("dt");dt.textContent=k;const dd=document.createElement("dd");dd.textContent=v;host.append(dt,dd)}
try{const r=await execAsync("if [ -f "+C.shellQuote(DATA+"/boot-status.txt")+" ]; then cat "+C.shellQuote(DATA+"/boot-status.txt")+"; else printf 'No boot apply has been recorded.'; fi");S.bootRaw=r.out;$("operationStatus").textContent=r.out||r.err||"No boot status";$("rawStatus").textContent=r.out||r.err||"No status file"}catch(e){$("operationStatus").textContent=e.message}
$("operationStatus").textContent+=(localStorage.getItem("lastOperation")?"\nWebUI: "+localStorage.getItem("lastOperation"):"");const errs=JSON.parse(localStorage.getItem("ls.errors")||"[]");if(errs.length)$("rawStatus").textContent+="\n\nRecent WebUI errors:\n"+errs.join("\n")}
function importPreview(){let incoming;try{incoming=C.parseJSON($("jsonBox").value)}catch(e){announce(e.message);return}const summary="Schema 1 · "+incoming.apps.length+" app entries · auto-apply "+(incoming.autoApplyOnBoot?"enabled":"disabled")+". Choose how these entries should be applied.";showImportDialog(summary,incoming)}
function showImportDialog(summary,incoming){const host=$("dialogHost");host.replaceChildren();const scrim=document.createElement("div");scrim.className="dialog-scrim";const d=document.createElement("div");d.className="dialog";const h=document.createElement("h2");h.textContent="Import settings";const p=document.createElement("p");p.textContent=summary;const row=document.createElement("div");row.className="dialog-actions";for(const mode of ["cancel","replace","merge"]){const b=document.createElement("button");b.textContent=mode==="cancel"?"Cancel":mode==="replace"?"Replace":"Merge";b.onclick=async()=>{host.replaceChildren();if(mode==="cancel")return;try{const result=mode==="merge"?C.mergeConfig(S.configs,incoming):incoming;await saveConfig(result);localStorage.setItem("configSavedAt",new Date().toLocaleString());announce("Settings imported ("+mode+")");$("importSummary").textContent=summary+" Imported by "+mode+"."; $("importSummary").classList.remove("hidden");$("autoSwitch").setAttribute("aria-checked",String(result.autoApplyOnBoot))}catch(e){recordError("Import: "+e.message);announce("Import failed: "+e.message)}};row.append(b)}d.append(h,p,row);scrim.append(d);host.append(scrim)}
function exportConfig(){const text=JSON.stringify(C.normalizeConfig(S.configs),null,2);$("jsonBox").value=text;$("importSummary").textContent="Export ready. Copy this JSON text and store it somewhere safe."; $("importSummary").classList.remove("hidden")}
async function copyText(){const box=$("jsonBox");try{await navigator.clipboard.writeText(box.value);announce("Copied")}catch(e){box.focus();box.select();try{document.execCommand("copy");announce("Copied")}catch(x){announce("Select and copy the text manually")}}}
function addNav(){document.querySelectorAll(".nav-button").forEach(b=>b.addEventListener("click",()=>setPage(b.dataset.page)));$("back").onclick=()=>{S.localeQuery=$("localeSearch").value;setPage("apps");renderApps()};$("refresh").onclick=()=>S.page==="detail"?openDetail(S.selected):loadApps();$("search").addEventListener("input",renderApps);$("localeSearch").addEventListener("input",()=>{S.localeQuery=$("localeSearch").value;renderLocales()});$("systemSwitch").onclick=()=>{S.showSystem=!S.showSystem;$("systemSwitch").setAttribute("aria-checked",String(S.showSystem));renderApps()};$("restoreDefault").onclick=restoreDefault;$("autoSwitch").onclick=async()=>{const next={...S.configs,autoApplyOnBoot:!S.configs.autoApplyOnBoot};try{await saveConfig(next);localStorage.setItem("configSavedAt",new Date().toLocaleString());announce(next.autoApplyOnBoot?"Boot apply enabled":"Boot apply disabled")}catch(e){announce("Could not save setting: "+e.message);recordError(e.message)}};$("exportBtn").onclick=exportConfig;$("previewImport").onclick=importPreview;$("copyJson").onclick=copyText;$("themeSelect").onchange=()=>{localStorage.setItem("ls.theme",$("themeSelect").value);theme()};$("accentColor").oninput=()=>{localStorage.setItem("ls.accent",$("accentColor").value);theme()};$("dialogHost").addEventListener("click",e=>{if(e.target.classList.contains("dialog-scrim"))e.currentTarget.replaceChildren()})}
function addRipple(){let start=null;document.addEventListener("pointerdown",e=>{const b=e.target.closest("button");if(!b)return;start={b,x:e.clientX,y:e.clientY,scroll:window.scrollY,type:e.pointerType}},true);document.addEventListener("pointerup",e=>{if(!start)return;const s=start;start=null;const limit=s.type==="mouse"?8:10;if(s.b!==e.target.closest("button")||Math.hypot(e.clientX-s.x,e.clientY-s.y)>limit||Math.abs(window.scrollY-s.scroll)>2)return;s.b.classList.add("tap");setTimeout(()=>s.b.classList.remove("tap"),360)},true)}
async function init(){theme();renderPresets();addNav();addRipple();await loadConfig();$("autoSwitch").setAttribute("aria-checked",String(S.configs.autoApplyOnBoot));if(S.configValid)$("configUpdated").textContent=localStorage.getItem("configSavedAt")||"Configuration loaded";addEventListener("pageshow",()=>theme());matchMedia("(prefers-color-scheme: dark)").addEventListener?.("change",()=>{if((localStorage.getItem("ls.theme")||"system")==="system")theme()});loadApps()}
document.addEventListener("DOMContentLoaded",init);
})();