(function(){
"use strict";
const C=window.LSCore;
const DATA="/data/adb/language_selector_ksu_data";
const CONFIG=DATA+"/config.v1";
const $=id=>document.getElementById(id);
const S={apps:[],selected:null,configs:{schemaVersion:1,autoApplyOnBoot:false,apps:[]},page:"apps",search:"",showSystem:false,loading:false,loadGeneration:0,errors:[],operation:"",bootRaw:"",configValid:false,localeQuery:""};
const BUNDLED_LOCALES=("af ar az be bg bn bs ca cs cy da de el en es et eu fa fi fil fr ga gl gu he hi hr hu hy id is it ja ka kk km kn ko lo lt lv mk ml mn mr ms mt my nb ne nl nn no pa pl pt ro ru sk sl sq sr sv sw ta te th uk ur uz vi zh zh-Hans zh-Hant en-US en-GB en-AU en-CA en-IN en-NZ en-SG en-ZA es-ES es-MX es-AR es-CO es-CL es-US fr-FR fr-CA fr-BE fr-CH pt-BR pt-PT zh-CN zh-TW zh-HK zh-SG zh-Hans-CN zh-Hant-TW zh-Hant-HK ja-JP ko-KR de-DE de-AT de-CH it-IT nl-NL nl-BE ru-RU uk-UA ar-EG ar-SA hi-IN bn-BD bn-IN pa-IN ta-IN ta-LK te-IN ur-PK fa-IR id-ID ms-MY th-TH vi-VN fil-PH tr-TR pl-PL cs-CZ sk-SK hu-HU ro-RO bg-BG el-GR he-IL sv-SE da-DK nb-NO fi-FI").split(" ");
let busy=false,initialized=false,uncertain=false;
function updateBusy(){document.querySelectorAll("#autoSwitch,#restoreDefault,.locale-option,.app-row").forEach(b=>b.disabled=busy||!initialized||uncertain);$("autoSwitch").disabled=busy||!initialized||uncertain||!S.configValid}
async function mutation(run){if(busy||!initialized||uncertain)return;busy=true;updateBusy();try{await run()}finally{busy=false;updateBusy();LSUI.bind()}}
let seq=0,DEVICE_LOCALES=[],LOCALE_CATALOG_SOURCE="离线备用语言列表";
function api(){return typeof window.ksu==="object"&&window.ksu}
function parseNative(v){if(Array.isArray(v))return v;if(typeof v==="string"){try{return JSON.parse(v)}catch(e){throw Error("KernelSU API returned invalid JSON")}}return []}
function execAsync(command){return new Promise((resolve,reject)=>{
const host=api();if(!host||(typeof host.spawn!=="function"&&typeof host.exec!=="function"))return reject(Error("KernelSU Next 异步执行 API 不可用"));
const name="__ls_cb_"+(++seq);let done=false,size=0;const stdout=[],stderr=[];
function finish(error,result){if(done)return;done=true;clearTimeout(timer);setTimeout(()=>delete window[name],1000);if(error)reject(error);else resolve(result)}
const timer=setTimeout(()=>{if(busy){uncertain=true;updateBusy()}finish(Error("Root 命令超时；不能确认是否完成。请刷新状态，勿重复应用。"))},30000);
if(typeof host.spawn==="function"){
const append=(target,data)=>{if(done)return;const text=String(data);size+=text.length;if(size<=1024*1024)target.push(text)};
window[name]={stdout:{emit:(event,data)=>{if(event==="data")append(stdout,data)}},stderr:{emit:(event,data)=>{if(event==="data")append(stderr,data)}},emit:(event,value)=>{if(event==="exit"){if(size>1024*1024)finish(Error("执行器输出超过限制"));else finish(null,{code:Number(value),out:stdout.join("\n"),err:stderr.join("\n")})}else if(event==="error")finish(Error(value?.message||"Root 命令启动失败"))}};
try{host.spawn("/system/bin/sh",JSON.stringify(["-c",C.shellQuote(command)]),"{}",name)}catch(e){finish(e)}
}else{
window[name]=(code,out,err)=>{if(done)return;if(String(out||"").length+String(err||"").length>1024*1024)finish(Error("执行器输出超过限制"));else finish(null,{code:Number(code),out:String(out||""),err:String(err||"")})};
try{host.exec(command,"{}",name)}catch(e){finish(e)}
}
})}
function command(parts){return parts.join(" ")}
function getUser(){return execAsync("am get-current-user").then(r=>{const u=r.out.trim();if(r.code!==0||!C.validUserId(u))throw Error("Unable to determine current Android user");return u})}
function localeCommand(action,pkg,user,tag){if(!C.validPackage(pkg))throw Error("Invalid package name");if(!C.validUserId(user))throw Error("Invalid Android user");const q=C.shellQuote;let p=["cmd","locale",action,q(pkg),"--user",q(user)];if(action==="set-app-locales"&&tag!==undefined){if(tag!==""&&!C.validLocale(tag))throw Error("Invalid BCP-47 Locale tag");if(tag!=="")p.push("--locales",q(tag))}return command(p)}
function checkPlatform(){const sdk=Number(localStorage.getItem("lastSdk")||0);if(sdk&&sdk<33)throw Error("Android 13 or later is required")}
async function readLocale(pkg,userOverride){try{checkPlatform();const user=userOverride===undefined?await getUser():userOverride;const r=await execAsync(localeCommand("get-app-locales",pkg,user));const parsed=C.parseLocaleOutput(r.out+"\n"+r.err);if(r.code!==0&&!parsed.ok)return{ok:false,reason:/not found|unknown command|not recognized/i.test(r.err+r.out)?"command-unavailable":parsed.reason,raw:r.err||r.out};if(!parsed.ok)return{ok:false,reason:parsed.reason,raw:parsed.raw};return parsed}catch(e){return{ok:false,reason:/Android 13/i.test(e.message)?"unsupported":/user/i.test(e.message)?"user-unavailable":"command-unavailable",raw:e.message}}}
function statusText(x){if(x===null||x===undefined)return "正在读取语言…";if(x&&x.ok)return x.followSystem?"跟随系统默认":x.localeTag||"已设置自定义语言";const map={"package-unavailable":"当前用户未安装或不可用","user-unavailable":"当前 Android 用户不可用","command-unavailable":"cmd locale 不可用或 ROM 不支持","unsupported":"需要 Android 13 或更高版本","read-failed":"无法读取应用语言"};return map[x?.reason]||"无法读取应用语言"}
function nativeList(){return C.packageNamesFromBridge(api())}
async function loadLocaleCatalog(){try{const r=await execAsync("cmd locale list-device-locales 2>&1");const tags=C.parseDeviceLocales(r.out);if(tags.length){DEVICE_LOCALES=tags;LOCALE_CATALOG_SOURCE="设备语言列表（"+tags.length+"）";if(S.page==="detail")renderLocales();return}}catch(e){}DEVICE_LOCALES=[];LOCALE_CATALOG_SOURCE="离线备用列表（"+BUNDLED_LOCALES.length+"）";if(S.page==="detail")renderLocales()}
async function loadConfig(){try{const r=await execAsync("if [ -f "+C.shellQuote(CONFIG)+" ]; then cat "+C.shellQuote(CONFIG)+"; else printf 'schema=1\\nauto=0\\n'; fi");if(r.code!==0)throw Error(r.err||"Cannot read config");S.configs=C.parseInternal(r.out);S.configValid=true}catch(e){S.configs={schemaVersion:1,autoApplyOnBoot:false,apps:[]};S.configValid=false;S.errors.push("Config: "+e.message)}}
async function saveConfig(next){const normalized=C.normalizeConfig(next),lines=C.toInternal(normalized).trimEnd().split("\n");const args=lines.map(C.shellQuote).join(" ");const q=C.shellQuote(CONFIG);const tmp=C.shellQuote(CONFIG+".tmp");const cmd="mkdir -p "+C.shellQuote(DATA)+" && chmod 0700 "+C.shellQuote(DATA)+" && printf '%s\\n' "+args+" > "+tmp+" && chmod 0600 "+tmp+" && mv -f "+tmp+" "+q;const r=await execAsync(cmd);if(r.code!==0)throw Error(r.err||r.out||"Configuration save failed");S.configs=normalized;S.configValid=true;localStorage.setItem("configSavedAt",new Date().toLocaleString());$("autoSwitch").setAttribute("aria-checked",String(normalized.autoApplyOnBoot));S.apps.forEach(updateLocaleRow)}
function appSetting(pkg){return S.configs.apps.find(a=>a.packageName===pkg)}
function updateEntry(pkg,entry){const apps=S.configs.apps.filter(a=>a.packageName!==pkg);apps.push({packageName:pkg,followSystem:entry.followSystem===true,localeTag:entry.followSystem?null:entry.localeTag});return{schemaVersion:1,autoApplyOnBoot:S.configs.autoApplyOnBoot,apps}}
function announce(text){const t=$("toast");t.textContent=text;t.classList.add("show");setTimeout(()=>t.classList.remove("show"),2400)}
function shellEscapeHtml(){}
function showDialog(title,message,actions){LSUI.showDialog(title,message,actions.map(a=>({...a,run:a.run?()=>mutation(a.run):undefined})))}
function theme(){LSUI.appearance()}
function setPage(page){LSUI.navigate(page)}
function renderDetail(app){S.selected=app;S.page="detail";$("appsPage").classList.add("hidden");$("detailPage").classList.remove("hidden");$("settingsPage").classList.add("hidden");if($("diagnosticsPage"))$("diagnosticsPage").classList.add("hidden");$("back").classList.remove("hidden");$("refresh").classList.remove("hidden");$("title").textContent="Language Selector";const head=$("appHeader");head.replaceChildren();const icon=document.createElement("img");icon.className="app-icon";icon.src=app.icon||("ksu://icon/"+encodeURIComponent(app.packageName));icon.alt="";const copy=document.createElement("div");const name=document.createElement("div");name.className="app-name";name.textContent=app.appLabel||app.packageName;const pkg=document.createElement("div");pkg.className="package";pkg.textContent=app.packageName;copy.append(name,pkg);head.append(icon,copy);const showResult=result=>{$("currentLocale").textContent=statusText(result)+(result&&result.ok&&!result.followSystem?" ("+result.localeTag+")":"");if(result&&!result.ok)recordError(app.packageName+": "+statusText(result)+" — "+result.raw)};document.querySelector(".bottom-nav").hidden=true;if(app.locale)$("currentLocale").textContent=statusText(app.locale)+(app.locale.ok&&!app.locale.followSystem?" ("+app.locale.localeTag+")":"");else $("currentLocale").textContent="正在读取语言…";renderLocales();updateBusy();readLocale(app.packageName).then(result=>{app.locale=result;updateLocaleRow(app);if(S.selected?.packageName===app.packageName&&S.page==="detail")showResult(result)})}
function openDetail(app){LSUI.navigate("detail",app);renderDetail(app)}
function langLabel(tag){const chinese={"zh-CN":"中文（简体，中国）","zh-Hans-CN":"中文（简体，中国）","zh-TW":"中文（繁体，台湾）","zh-Hant-TW":"中文（繁体，台湾）","zh-Hans":"中文（简体）","zh-Hant":"中文（繁体）"};if(chinese[tag])return chinese[tag];try{const [lang,...rest]=tag.split("-");const disp=new Intl.DisplayNames([navigator.language||"en"],{type:"language"});const base=disp.of(lang);return rest.length?base+" · "+rest.join("-"):base}catch(e){return tag}}
function renderLocales(){const q=S.localeQuery.trim().toLowerCase();for(const id of ["commonLocales","localeList"]){const host=$(id);host.replaceChildren();const catalog=DEVICE_LOCALES.length?DEVICE_LOCALES:BUNDLED_LOCALES;const common=C.commonLocales(catalog);const list=id==="commonLocales"?common:catalog.filter(t=>!common.includes(t));const tags=[...new Set(list)].filter(C.validLocale).filter(t=>!q||t.toLowerCase().includes(q)||langLabel(t).toLowerCase().includes(q));if(!tags.length){const empty=document.createElement("div");empty.className="empty-state";empty.textContent=id==="commonLocales"?"暂无常用语言":"暂无可用语言";host.append(empty);continue}for(const tag of tags){const b=document.createElement("button");b.className="locale-option";b.innerHTML="";const title=document.createElement("span");title.textContent=langLabel(tag);const sub=document.createElement("small");sub.textContent=tag;b.append(title,sub);b.onclick=()=>applyLocale(tag);b.setAttribute("aria-pressed",String(S.selected?.locale?.ok&&S.selected.locale.localeTag===tag));host.append(b)}}LSUI.bind();updateBusy()}
async function applyLocale(tag){const app=S.selected;if(!app||!C.validLocale(tag))return;showDialog("应用语言","将 "+tag+" 设置到 "+app.packageName+"？应用可能需要重新启动才能显示变化。",[{label:"取消"},{label:"应用",run:async()=>{await performLocale(app,tag)}}])}
async function restoreDefault(){const app=S.selected;if(!app)return;showDialog("跟随系统默认","清除 "+app.packageName+" 的应用专属语言设置？",[{label:"取消"},{label:"恢复",run:async()=>{await performLocale(app,null)}}])}
async function performLocale(app,tag){announce("正在应用…");try{checkPlatform();const user=await getUser();const cmd=tag===null?localeCommand("set-app-locales",app.packageName,user):localeCommand("set-app-locales",app.packageName,user,tag);const result=await execAsync(cmd);if(result.code!==0)throw Error(result.err||result.out||"cmd locale 返回 "+result.code);const actual=await readLocale(app.packageName,user);app.locale=actual;updateLocaleRow(app);const matches=actual.ok&&(tag===null?actual.followSystem:(!actual.followSystem&&C.sameLocale(actual.localeTag.split(",")[0].trim(),tag)));if(!matches)throw Error(actual.ok?"命令返回成功但验证不匹配："+statusText(actual):statusText(actual)+" "+actual.raw);try{await saveConfig(updateEntry(app.packageName,{followSystem:tag===null,localeTag:tag}))}catch(e){recordError("语言已修改，但配置保存失败："+e.message);$("currentLocale").textContent="语言已应用，但配置保存失败";announce("语言已应用，但保存失败");return}S.operation=(tag===null?"已恢复系统默认：":"已设置 "+tag+"：")+app.packageName;localStorage.setItem("lastOperation",S.operation);$("currentLocale").textContent=tag===null?"跟随系统默认":tag;announce("已验证："+(tag||"系统默认"))}catch(e){recordError(e.message);S.operation="失败："+app.packageName+" — "+e.message;localStorage.setItem("lastOperation",S.operation);$("currentLocale").textContent="失败："+e.message;announce("语言设置失败")}}
function recordError(x){S.errors.unshift(new Date().toISOString()+" "+x);S.errors=S.errors.slice(0,30);localStorage.setItem("ls.errors",JSON.stringify(S.errors))}
function iconData(value){if(!value)return"";if(value.startsWith("data:image"))return value;return"data:image/png;base64,"+value}
async function yieldTask(){return new Promise(resolve=>setTimeout(resolve,0))}
function parsePmPackages(output){return C.packageNamesFromPm(output)}
async function shellPackageList(){const user=await getUser(),q=C.shellQuote;async function run(flag){return execAsync("cmd package list packages --user "+q(user)+" "+flag+" 2>&1")}let system=[],userApps=[];const sr=await run("-s"),ur=await run("-3");if(sr.code===0)system=parsePmPackages(sr.out);if(ur.code===0)userApps=parsePmPackages(ur.out);if(!system.length&&!userApps.length){const all=await run("");if(all.code!==0)throw Error(all.err||all.out||"Package Manager could not list installed apps");return parsePmPackages(all.out).map(packageName=>({packageName,isSystem:false}))}const systemSet=new Set(system);return [...new Set([...system,...userApps])].map(packageName=>({packageName,isSystem:systemSet.has(packageName)}))}
async function loadApps(){if(S.loading)return;const generation=++S.loadGeneration;S.loading=true;$("listStatus").textContent="正在加载已安装应用…";$("appList").replaceChildren();try{let names=nativeList(),shellEntries=null;if(!names){shellEntries=await shellPackageList();names=shellEntries.map(x=>x.packageName)}const unique=[...new Set(names.filter(C.validPackage))];if(!unique.length){$("listStatus").textContent="未返回已安装应用，请检查 Manager 的 Shell 权限。";S.apps=[];return}
const all=[];if(api()&&typeof ksu.getPackagesInfo==="function"){for(let i=0;i<unique.length;i+=50){const batch=unique.slice(i,i+50);try{const infos=parseNative(ksu.getPackagesInfo(JSON.stringify(batch)));if(Array.isArray(infos))all.push(...infos.filter(x=>!x.error))}catch(e){S.errors.push("Some app labels could not be read: "+e.message)}$("listStatus").textContent="正在读取应用信息… "+Math.min(i+50,unique.length)+" / "+unique.length;await yieldTask()}}
let icons=[];if(api()&&typeof ksu.getPackagesIcons==="function"){for(let i=0;i<unique.length;i+=40){try{icons.push(...parseNative(ksu.getPackagesIcons(JSON.stringify(unique.slice(i,i+40)),48)))}catch(e){break}await yieldTask()}}
const iconMap=new Map(icons.map(x=>[x.packageName,iconData(x.icon)])),infoMap=new Map(all.map(x=>[x.packageName,x])),systemMap=new Map((shellEntries||[]).map(x=>[x.packageName,x.isSystem]));S.apps=unique.map(pkg=>{const x=infoMap.get(pkg)||{};return{packageName:pkg,appLabel:x.appLabel||pkg,isSystem:typeof x.isSystem==="boolean"?x.isSystem:!!systemMap.get(pkg),icon:iconMap.get(pkg)||"",locale:null}});$("listStatus").textContent="应用已加载 · 正在读取语言状态…";renderApps();const apps=S.apps;void(async()=>{let user=null,userError=null;try{user=await getUser()}catch(e){userError=e}let i=0,at=0;async function worker(){while(at<apps.length){if(generation!==S.loadGeneration)return;const item=apps[at++];item.locale=userError?{ok:false,reason:"user-unavailable",raw:userError.message}:await readLocale(item.packageName,user);updateLocaleRow(item);i++;if(i%15===0||i===apps.length){if(generation===S.loadGeneration)$("listStatus").textContent= "正在读取应用语言… "+i+" / "+apps.length}await yieldTask()}}await Promise.all(Array.from({length:6},worker));if(generation===S.loadGeneration){const failed=apps.filter(x=>!x.locale?.ok).length;$("listStatus").textContent=apps.length+" 个应用已加载"+(shellEntries?" · 系统包管理器":"")+(failed?" · "+failed+" 个应用语言状态不可用":"")}})()}catch(e){$("listStatus").textContent="无法加载应用："+e.message;S.errors.unshift(e.message);recordError("App list: "+e.message)}finally{S.loading=false}}
let reorderFrame=null;
function scheduleAppOrder(){if(reorderFrame!==null)return;reorderFrame=requestAnimationFrame(()=>{reorderFrame=null;const host=$("appList"),rows=[...host.children].filter(row=>row.dataset.packageName),byPackage=new Map(rows.map(row=>[row.dataset.packageName,row])),ordered=C.sortAppsByLocale(S.apps,S.configs.apps).map(app=>byPackage.get(app.packageName)).filter(Boolean);if(ordered.every((row,index)=>row===rows[index]))return;const scroll=$("main").scrollTop,focus=document.activeElement;ordered.forEach((row,index)=>{if(host.children[index]!==row)host.insertBefore(row,host.children[index]||null)});if(focus?.isConnected&&document.activeElement!==focus)focus.focus({preventScroll:true});$("main").scrollTop=scroll;});}
function decorateLocaleRow(row,app){
 const setting=C.moduleLocale(app,S.configs.apps),state=row.querySelector(".locale-state"),badge=row.querySelector(".module-setting");
 row.classList.toggle("module-configured",!!setting);
 badge.hidden=!setting;
 badge.textContent=setting?"已在模块中设置为 "+langLabel(setting.localeTag):"";
 if(setting){badge.title=setting.localeTag;state.textContent=!app.locale?"正在核对当前语言…":!app.locale.ok?statusText(app.locale):C.sameLocale(app.locale.localeTag,setting.localeTag)&&!app.locale.followSystem?"当前语言与模块配置一致":"当前语言："+(app.locale.followSystem?"系统默认":langLabel(app.locale.localeTag))+" · 与模块配置不同"}
 else{badge.removeAttribute("title");state.textContent=app.locale?.ok&&!app.locale.followSystem?"当前语言："+langLabel(app.locale.localeTag):statusText(app.locale)}
}
function updateLocaleRow(app){const row=[...$("appList").children].find(node=>node.dataset.packageName===app.packageName);if(row)decorateLocaleRow(row,app);scheduleAppOrder()}
function renderApps(){const host=$("appList");host.replaceChildren();const query=$("search").value.trim().toLowerCase();const list=C.sortAppsByLocale(S.apps,S.configs.apps).filter(a=>(S.showSystem||!a.isSystem)&&(!query||a.appLabel.toLowerCase().includes(query)||a.packageName.toLowerCase().includes(query)));if(!list.length){const p=document.createElement("div");p.className="statusline";p.textContent=S.apps.length?"没有匹配的应用。":"没有可用应用。";host.append(p);return}for(const app of list){const b=document.createElement("button");b.className="app-row";b.dataset.packageName=app.packageName;const img=document.createElement("img");img.className="app-icon";img.alt="";img.src=app.icon||("ksu://icon/"+encodeURIComponent(app.packageName));img.onerror=()=>{img.onerror=null;img.src="data:image/svg+xml,"+encodeURIComponent('<svg xmlns="http://www.w3.org/2000/svg" width="48" height="48"><rect width="48" height="48" fill="#eeeeee"/><text x="24" y="30" text-anchor="middle" font-size="20" fill="#757575">'+(app.appLabel||"?").slice(0,1).replace(/[<&]/g,"")+'</text></svg>')};const copy=document.createElement("div");copy.className="app-copy";const name=document.createElement("div");name.className="app-name";name.textContent=app.appLabel;const pkg=document.createElement("div");pkg.className="package";pkg.textContent=app.packageName;const loc=document.createElement("div");loc.className="locale-state";loc.textContent=statusText(app.locale);const badge=document.createElement("div");badge.className="module-setting";copy.append(name,pkg,badge,loc);b.append(img,copy);decorateLocaleRow(b,app);b.onclick=()=>openDetail(app);host.append(b)}LSUI.bind();updateBusy()}
async function loadDiagnostics(){const host=$("diagnostics");host.replaceChildren();const rows=[];let sys="",sdk="",cmd="";try{const r=await execAsync("getprop ro.build.version.release; getprop ro.build.version.sdk");[sys,sdk]=r.out.trim().split(/\r?\n/)}catch(e){}localStorage.setItem("lastSdk",sdk||"0");try{const r=await execAsync("command -v cmd >/dev/null 2>&1 || { printf unavailable; exit; }; help=$(cmd locale help 2>&1); case \"$help\" in *get-app-locales*) case \"$help\" in *set-app-locales*) printf available;; *) printf unavailable;; esac;; *) printf unavailable;; esac");cmd=r.out.trim()}catch(e){cmd="unavailable"}rows.push(["Android",sys?sys+" (API "+sdk+")":"不可用"],["KernelSU Next API",api()&&(typeof ksu.spawn==="function"||typeof ksu.exec==="function")?(C.packageNamesFromBridge(api())?"应用接口可用":"系统 Shell 可用"):"Root 接口不可用"],["应用图标",api()&&typeof ksu.getPackagesIcons==="function"?"可用":"宿主图标回退"],["cmd locale",cmd==="available"?"可用":"不可用"],["语言列表",LOCALE_CATALOG_SOURCE],["配置",S.configValid?"已校验":"读取失败，开机应用禁用"],["最近保存",localStorage.getItem("configSavedAt")||"暂无记录"]);for(const [k,v]of rows){const dt=document.createElement("dt");dt.textContent=k;const dd=document.createElement("dd");dd.textContent=v;host.append(dt,dd)}
try{const r=await execAsync("if [ -f "+C.shellQuote(DATA+"/boot-status.txt")+" ]; then cat "+C.shellQuote(DATA+"/boot-status.txt")+"; else printf 'No boot apply has been recorded.'; fi");S.bootRaw=r.out;const summary=/^summary=(.*)$/m.exec(r.out)?.[1];const success=/^success=(\d+)$/m.exec(r.out)?.[1]||"0",failed=/^failed=(\d+)$/m.exec(r.out)?.[1]||"0";$("operationStatus").textContent=summary==="boot apply disabled"?"开机应用已关闭":summary?"上次开机应用：成功 "+success+"，失败 "+failed:"暂无开机应用记录";$("rawStatus").textContent=r.out||r.err||"暂无状态文件"}catch(e){$("operationStatus").textContent=e.message}
$("operationStatus").textContent+=(localStorage.getItem("lastOperation")?"\n最近设置："+localStorage.getItem("lastOperation"):"");let errs=[];try{const saved=JSON.parse(localStorage.getItem("ls.errors")||"[]");if(Array.isArray(saved))errs=saved}catch(_){}if(errs.length)$("rawStatus").textContent+="\n\nRecent WebUI errors:\n"+errs.join("\n")}
function installTapFeedback(){LSUI.bind()}
function addNav(){
LSUI.init({page:page=>{S.page=page},detail:pkg=>{const app=S.apps.find(x=>x.packageName===pkg)||S.selected;if(!app||app.packageName!==pkg)return false;renderDetail(app);return true},diagnostics:loadDiagnostics,error:e=>{recordError(e.message);announce(e.message)}});
$("refresh").onclick=()=>S.page==="detail"?renderDetail(S.selected):loadApps();
function bindSearch(id,changed){
 const input=$(id),clear=$(id+"Clear");let composing=false;
 const sync=()=>{clear.hidden=!input.value};
 input.addEventListener("compositionstart",()=>{composing=true});
 input.addEventListener("compositionend",()=>{composing=false;sync();changed()});
 input.addEventListener("input",event=>{sync();if(!composing&&!event.isComposing)changed()});
 clear.addEventListener("pointerdown",event=>event.preventDefault());
 clear.onclick=()=>{input.value="";composing=false;sync();input.focus({preventScroll:true});changed()};
 sync();
}
bindSearch("search",renderApps);
bindSearch("localeSearch",()=>{S.localeQuery=$("localeSearch").value;renderLocales()});
$("systemSwitch").onclick=()=>{S.showSystem=!S.showSystem;$("systemSwitch").setAttribute("aria-checked",String(S.showSystem));renderApps()};
$("restoreDefault").onclick=restoreDefault;
$("autoSwitch").onclick=()=>mutation(async()=>{const next={...S.configs,autoApplyOnBoot:!S.configs.autoApplyOnBoot};try{await saveConfig(next);announce(next.autoApplyOnBoot?"已开启开机应用":"已关闭开机应用")}catch(e){announce("设置保存失败："+e.message);recordError(e.message)}});
}
async function init(){
addNav();updateBusy();const slow=setTimeout(()=>window.LSReady(),6000);
try{await loadConfig();await loadLocaleCatalog();$("autoSwitch").setAttribute("aria-checked",String(S.configs.autoApplyOnBoot));await loadApps();}
finally{clearTimeout(slow);initialized=true;updateBusy();window.LSReady();}
}
document.addEventListener("DOMContentLoaded",init);
})();
